sonar.projectKey=mytime_sb_19
sonar.host.url=http://sonarqube.unternhub.at
sonar.issue.ignore.multicriteria=e22,e23,e24,e25,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14,e15,e16,e17,e18,e19,e20,e26,e27,e28
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**
sonar.issue.ignore.multicriteria.e2.ruleKey=xml:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S125
sonar.issue.ignore.multicriteria.e3.resourceKey=**
sonar.issue.ignore.multicriteria.e4.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e4.resourceKey=**
sonar.issue.ignore.multicriteria.e5.ruleKey=python:S2245
sonar.issue.ignore.multicriteria.e5.resourceKey=**
sonar.issue.ignore.multicriteria.e6.ruleKey=Web:S6850
sonar.issue.ignore.multicriteria.e6.resourceKey=**
sonar.issue.ignore.multicriteria.e7.ruleKey=javascript:S2245
sonar.issue.ignore.multicriteria.e7.resourceKey=**
sonar.issue.ignore.multicriteria.e8.ruleKey=python:S5332
sonar.issue.ignore.multicriteria.e8.resourceKey=**
sonar.issue.ignore.multicriteria.e9.ruleKey=python:S5443
sonar.issue.ignore.multicriteria.e9.resourceKey=**
# hardcoded ip false positive version
sonar.issue.ignore.multicriteria.e10.ruleKey=python:S1313
sonar.issue.ignore.multicriteria.e10.resourceKey=**
# <script in html
sonar.issue.ignore.multicriteria.e11.ruleKey=Web:S5725
sonar.issue.ignore.multicriteria.e11.resourceKey=**
#regex
sonar.issue.ignore.multicriteria.e12.ruleKey=python:S5852
sonar.issue.ignore.multicriteria.e12.resourceKey=**
sonar.issue.ignore.multicriteria.e13.ruleKey=javascript:S5852
sonar.issue.ignore.multicriteria.e13.resourceKey=**
sonar.issue.ignore.multicriteria.e14.ruleKey=javascript:S5332
sonar.issue.ignore.multicriteria.e14.resourceKey=**
# let instead of const/var common practice in odoo to use var
# in certain situations
sonar.issue.ignore.multicriteria.e15.ruleKey=javascript:S3504
sonar.issue.ignore.multicriteria.e15.resourceKey=**
# because of return this._super.apply(this, arguments)
sonar.issue.ignore.multicriteria.e16.ruleKey=javascript:S6666
sonar.issue.ignore.multicriteria.e16.resourceKey=**
sonar.issue.ignore.multicriteria.e17.ruleKey=python:S5799
sonar.issue.ignore.multicriteria.e17.resourceKey=**
sonar.issue.ignore.multicriteria.e18.ruleKey=python:S117
sonar.issue.ignore.multicriteria.e18.resourceKey=**
# there are to many diviating class names in Odoo standard eg. Im_LivechatChannelRule
# to match the regular expression ^_?([A-Z_][a-zA-Z0-9]*|[a-z_][a-z0-9_]*)$.
sonar.issue.ignore.multicriteria.e19.ruleKey=python:S101
sonar.issue.ignore.multicriteria.e19.resourceKey=**

#ToDo:
sonar.issue.ignore.multicriteria.e20.ruleKey=python:S1515
sonar.issue.ignore.multicriteria.e20.resourceKey=**
sonar.issue.ignore.multicriteria.e22.ruleKey=javascript:S7728
sonar.issue.ignore.multicriteria.e22.resourceKey=**
sonar.issue.ignore.multicriteria.e23.ruleKey=javascript:S7764
sonar.issue.ignore.multicriteria.e23.resourceKey=**
sonar.issue.ignore.multicriteria.e24.ruleKey=javascript:S7773
sonar.issue.ignore.multicriteria.e24.resourceKey=**
sonar.issue.ignore.multicriteria.e25.ruleKey=javascript:S4138
sonar.issue.ignore.multicriteria.e25.resourceKey=**
sonar.issue.ignore.multicriteria.e26.ruleKey=javascript:S5604 # gps is necessary for this application
sonar.issue.ignore.multicriteria.e26.resourceKey=**
sonar.issue.ignore.multicriteria.e27.ruleKey=python:S1481 # error prone
sonar.issue.ignore.multicriteria.e27.resourceKey=**

#
sonar.issue.ignore.multicriteria.e28.ruleKey=css:S4667
sonar.issue.ignore.multicriteria.e28.resourceKey=**

sonar.cpd.exclusions=**/static/description/index.html,**/description/index.html
sonar.py.version=3.9, 3.10, 3.11, 3.12
sonar.python.version=3.12
sonar.projectVersion=1.0.3
#sonar.newCode.referenceDate=2025-07-01
sonar.scm.disabled=true
sonar.sourceEncoding=UTF-8
sonar.newCode.exclusions=**/bulletin_board_addresses/**
sonar.exclusions=**/misc/**,**/libs/**,**/lib/**,**/index.html,**/.git/**,**/node_modules/**,**/__pycache__/**,**/venv_*/**,**/*.zip,**/*.tar,**/*.gz,**/*.pack
sonar.python.coverage.reportPaths=coverage-reports/*coverage-*.xml
sonar.sources=.
